<?
$PERM["sale_personalization.php"]["13"]="D";
$PERM["fileman_doc_roots.php"]["13"]="D";
$PERM["fileman_admin.php"]["13"]="D";
$PERM["sale_affiliate_tier.php"]["13"]="D";
$PERM["sale_affiliate_plan.php"]["13"]="D";
$PERM["sale_affiliate_transact.php"]["13"]="D";
$PERM["sale_affiliate.php"]["13"]="D";
$PERM["sale_affiliate_calc.php"]["13"]="D";
$PERM["sale_stat_graph_money.php"]["13"]="D";
$PERM["sale_stat_graph_index.php"]["13"]="D";
$PERM["sale_stat_products.php"]["13"]="D";
$PERM["sale_stat.php"]["13"]="D";
$PERM["sale_report.php"]["13"]="D";
$PERM["sale_recurring_admin.php"]["13"]="D";
$PERM["sale_transact_admin.php"]["13"]="D";
$PERM["sale_account_admin.php"]["13"]="D";
$PERM["sale_basket.php"]["13"]="D";
$PERM["sale_buyers.php"]["13"]="D";
$PERM["sale_order.php"]["5"]="R";
?>